//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDocuments.ServiceSolicitud {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auditoria", Namespace="http://schemas.datacontract.org/2004/07/eDocuments.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDocuments.ServiceSolicitud.BESeguimientoSolicitud))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDocuments.ServiceSolicitud.BESolicitud))]
    public partial class Auditoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime aud_fec_ingresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime aud_fec_modificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aud_usr_ingresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aud_usr_modificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_estado_registroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime aud_fec_ingreso {
            get {
                return this.aud_fec_ingresoField;
            }
            set {
                if ((this.aud_fec_ingresoField.Equals(value) != true)) {
                    this.aud_fec_ingresoField = value;
                    this.RaisePropertyChanged("aud_fec_ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime aud_fec_modificacion {
            get {
                return this.aud_fec_modificacionField;
            }
            set {
                if ((this.aud_fec_modificacionField.Equals(value) != true)) {
                    this.aud_fec_modificacionField = value;
                    this.RaisePropertyChanged("aud_fec_modificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aud_usr_ingreso {
            get {
                return this.aud_usr_ingresoField;
            }
            set {
                if ((object.ReferenceEquals(this.aud_usr_ingresoField, value) != true)) {
                    this.aud_usr_ingresoField = value;
                    this.RaisePropertyChanged("aud_usr_ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aud_usr_modificacion {
            get {
                return this.aud_usr_modificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.aud_usr_modificacionField, value) != true)) {
                    this.aud_usr_modificacionField = value;
                    this.RaisePropertyChanged("aud_usr_modificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_estado_registro {
            get {
                return this.cod_estado_registroField;
            }
            set {
                if ((this.cod_estado_registroField.Equals(value) != true)) {
                    this.cod_estado_registroField = value;
                    this.RaisePropertyChanged("cod_estado_registro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BESeguimientoSolicitud", Namespace="http://schemas.datacontract.org/2004/07/eDocuments.Entities")]
    [System.SerializableAttribute()]
    public partial class BESeguimientoSolicitud : WebDocuments.ServiceSolicitud.Auditoria {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_seguimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_solicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gls_observacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_estado {
            get {
                return this.cod_estadoField;
            }
            set {
                if ((this.cod_estadoField.Equals(value) != true)) {
                    this.cod_estadoField = value;
                    this.RaisePropertyChanged("cod_estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_seguimiento {
            get {
                return this.cod_seguimientoField;
            }
            set {
                if ((this.cod_seguimientoField.Equals(value) != true)) {
                    this.cod_seguimientoField = value;
                    this.RaisePropertyChanged("cod_seguimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_solicitud {
            get {
                return this.cod_solicitudField;
            }
            set {
                if ((this.cod_solicitudField.Equals(value) != true)) {
                    this.cod_solicitudField = value;
                    this.RaisePropertyChanged("cod_solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gls_observacion {
            get {
                return this.gls_observacionField;
            }
            set {
                if ((object.ReferenceEquals(this.gls_observacionField, value) != true)) {
                    this.gls_observacionField = value;
                    this.RaisePropertyChanged("gls_observacion");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BESolicitud", Namespace="http://schemas.datacontract.org/2004/07/eDocuments.Entities")]
    [System.SerializableAttribute()]
    public partial class BESolicitud : WebDocuments.ServiceSolicitud.Auditoria {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_solicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gls_solicitudField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_documento {
            get {
                return this.cod_documentoField;
            }
            set {
                if ((this.cod_documentoField.Equals(value) != true)) {
                    this.cod_documentoField = value;
                    this.RaisePropertyChanged("cod_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_estado {
            get {
                return this.cod_estadoField;
            }
            set {
                if ((this.cod_estadoField.Equals(value) != true)) {
                    this.cod_estadoField = value;
                    this.RaisePropertyChanged("cod_estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_solicitud {
            get {
                return this.cod_solicitudField;
            }
            set {
                if ((this.cod_solicitudField.Equals(value) != true)) {
                    this.cod_solicitudField = value;
                    this.RaisePropertyChanged("cod_solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gls_solicitud {
            get {
                return this.gls_solicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.gls_solicitudField, value) != true)) {
                    this.gls_solicitudField = value;
                    this.RaisePropertyChanged("gls_solicitud");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSolicitud.ISolicitudService")]
    public interface ISolicitudService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudService/RegistrarSolicitud", ReplyAction="http://tempuri.org/ISolicitudService/RegistrarSolicitudResponse")]
        int RegistrarSolicitud(WebDocuments.ServiceSolicitud.BESolicitud oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudService/RegistrarSolicitud", ReplyAction="http://tempuri.org/ISolicitudService/RegistrarSolicitudResponse")]
        System.Threading.Tasks.Task<int> RegistrarSolicitudAsync(WebDocuments.ServiceSolicitud.BESolicitud oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudService/ModificarSolicitud", ReplyAction="http://tempuri.org/ISolicitudService/ModificarSolicitudResponse")]
        bool ModificarSolicitud(WebDocuments.ServiceSolicitud.BESolicitud oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudService/ModificarSolicitud", ReplyAction="http://tempuri.org/ISolicitudService/ModificarSolicitudResponse")]
        System.Threading.Tasks.Task<bool> ModificarSolicitudAsync(WebDocuments.ServiceSolicitud.BESolicitud oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudService/ObtenerSolicitud", ReplyAction="http://tempuri.org/ISolicitudService/ObtenerSolicitudResponse")]
        WebDocuments.ServiceSolicitud.BESolicitud ObtenerSolicitud(int cod_solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudService/ObtenerSolicitud", ReplyAction="http://tempuri.org/ISolicitudService/ObtenerSolicitudResponse")]
        System.Threading.Tasks.Task<WebDocuments.ServiceSolicitud.BESolicitud> ObtenerSolicitudAsync(int cod_solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudService/EliminarSolicitud", ReplyAction="http://tempuri.org/ISolicitudService/EliminarSolicitudResponse")]
        int EliminarSolicitud(WebDocuments.ServiceSolicitud.BESolicitud oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudService/EliminarSolicitud", ReplyAction="http://tempuri.org/ISolicitudService/EliminarSolicitudResponse")]
        System.Threading.Tasks.Task<int> EliminarSolicitudAsync(WebDocuments.ServiceSolicitud.BESolicitud oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudService/RegistrarSeguimientoSolicitud", ReplyAction="http://tempuri.org/ISolicitudService/RegistrarSeguimientoSolicitudResponse")]
        int RegistrarSeguimientoSolicitud(WebDocuments.ServiceSolicitud.BESeguimientoSolicitud oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudService/RegistrarSeguimientoSolicitud", ReplyAction="http://tempuri.org/ISolicitudService/RegistrarSeguimientoSolicitudResponse")]
        System.Threading.Tasks.Task<int> RegistrarSeguimientoSolicitudAsync(WebDocuments.ServiceSolicitud.BESeguimientoSolicitud oParametro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISolicitudServiceChannel : WebDocuments.ServiceSolicitud.ISolicitudService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SolicitudServiceClient : System.ServiceModel.ClientBase<WebDocuments.ServiceSolicitud.ISolicitudService>, WebDocuments.ServiceSolicitud.ISolicitudService {
        
        public SolicitudServiceClient() {
        }
        
        public SolicitudServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SolicitudServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitudServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitudServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RegistrarSolicitud(WebDocuments.ServiceSolicitud.BESolicitud oParametro) {
            return base.Channel.RegistrarSolicitud(oParametro);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarSolicitudAsync(WebDocuments.ServiceSolicitud.BESolicitud oParametro) {
            return base.Channel.RegistrarSolicitudAsync(oParametro);
        }
        
        public bool ModificarSolicitud(WebDocuments.ServiceSolicitud.BESolicitud oParametro) {
            return base.Channel.ModificarSolicitud(oParametro);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarSolicitudAsync(WebDocuments.ServiceSolicitud.BESolicitud oParametro) {
            return base.Channel.ModificarSolicitudAsync(oParametro);
        }
        
        public WebDocuments.ServiceSolicitud.BESolicitud ObtenerSolicitud(int cod_solicitud) {
            return base.Channel.ObtenerSolicitud(cod_solicitud);
        }
        
        public System.Threading.Tasks.Task<WebDocuments.ServiceSolicitud.BESolicitud> ObtenerSolicitudAsync(int cod_solicitud) {
            return base.Channel.ObtenerSolicitudAsync(cod_solicitud);
        }
        
        public int EliminarSolicitud(WebDocuments.ServiceSolicitud.BESolicitud oParametro) {
            return base.Channel.EliminarSolicitud(oParametro);
        }
        
        public System.Threading.Tasks.Task<int> EliminarSolicitudAsync(WebDocuments.ServiceSolicitud.BESolicitud oParametro) {
            return base.Channel.EliminarSolicitudAsync(oParametro);
        }
        
        public int RegistrarSeguimientoSolicitud(WebDocuments.ServiceSolicitud.BESeguimientoSolicitud oParametro) {
            return base.Channel.RegistrarSeguimientoSolicitud(oParametro);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarSeguimientoSolicitudAsync(WebDocuments.ServiceSolicitud.BESeguimientoSolicitud oParametro) {
            return base.Channel.RegistrarSeguimientoSolicitudAsync(oParametro);
        }
    }
}
