//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDocuments.ServiceGeneral {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEArea", Namespace="http://schemas.datacontract.org/2004/07/eDocuments.Entities")]
    [System.SerializableAttribute()]
    public partial class BEArea : WebDocuments.ServiceGeneral.Auditoria {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_areaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gls_areaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_area {
            get {
                return this.cod_areaField;
            }
            set {
                if ((this.cod_areaField.Equals(value) != true)) {
                    this.cod_areaField = value;
                    this.RaisePropertyChanged("cod_area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gls_area {
            get {
                return this.gls_areaField;
            }
            set {
                if ((object.ReferenceEquals(this.gls_areaField, value) != true)) {
                    this.gls_areaField = value;
                    this.RaisePropertyChanged("gls_area");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auditoria", Namespace="http://schemas.datacontract.org/2004/07/eDocuments.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDocuments.ServiceGeneral.BERol))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDocuments.ServiceGeneral.BETipoDocumento))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDocuments.ServiceGeneral.BEEstado))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDocuments.ServiceGeneral.BEArea))]
    public partial class Auditoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime aud_fec_ingresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime aud_fec_modificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aud_usr_ingresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aud_usr_modificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_estado_registroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime aud_fec_ingreso {
            get {
                return this.aud_fec_ingresoField;
            }
            set {
                if ((this.aud_fec_ingresoField.Equals(value) != true)) {
                    this.aud_fec_ingresoField = value;
                    this.RaisePropertyChanged("aud_fec_ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime aud_fec_modificacion {
            get {
                return this.aud_fec_modificacionField;
            }
            set {
                if ((this.aud_fec_modificacionField.Equals(value) != true)) {
                    this.aud_fec_modificacionField = value;
                    this.RaisePropertyChanged("aud_fec_modificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aud_usr_ingreso {
            get {
                return this.aud_usr_ingresoField;
            }
            set {
                if ((object.ReferenceEquals(this.aud_usr_ingresoField, value) != true)) {
                    this.aud_usr_ingresoField = value;
                    this.RaisePropertyChanged("aud_usr_ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aud_usr_modificacion {
            get {
                return this.aud_usr_modificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.aud_usr_modificacionField, value) != true)) {
                    this.aud_usr_modificacionField = value;
                    this.RaisePropertyChanged("aud_usr_modificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_estado_registro {
            get {
                return this.cod_estado_registroField;
            }
            set {
                if ((this.cod_estado_registroField.Equals(value) != true)) {
                    this.cod_estado_registroField = value;
                    this.RaisePropertyChanged("cod_estado_registro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BERol", Namespace="http://schemas.datacontract.org/2004/07/eDocuments.Entities")]
    [System.SerializableAttribute()]
    public partial class BERol : WebDocuments.ServiceGeneral.Auditoria {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_rolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gls_rolField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_rol {
            get {
                return this.cod_rolField;
            }
            set {
                if ((this.cod_rolField.Equals(value) != true)) {
                    this.cod_rolField = value;
                    this.RaisePropertyChanged("cod_rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gls_rol {
            get {
                return this.gls_rolField;
            }
            set {
                if ((object.ReferenceEquals(this.gls_rolField, value) != true)) {
                    this.gls_rolField = value;
                    this.RaisePropertyChanged("gls_rol");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BETipoDocumento", Namespace="http://schemas.datacontract.org/2004/07/eDocuments.Entities")]
    [System.SerializableAttribute()]
    public partial class BETipoDocumento : WebDocuments.ServiceGeneral.Auditoria {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_tipo_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gls_tipo_documentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_tipo_documento {
            get {
                return this.cod_tipo_documentoField;
            }
            set {
                if ((this.cod_tipo_documentoField.Equals(value) != true)) {
                    this.cod_tipo_documentoField = value;
                    this.RaisePropertyChanged("cod_tipo_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gls_tipo_documento {
            get {
                return this.gls_tipo_documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.gls_tipo_documentoField, value) != true)) {
                    this.gls_tipo_documentoField = value;
                    this.RaisePropertyChanged("gls_tipo_documento");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEEstado", Namespace="http://schemas.datacontract.org/2004/07/eDocuments.Entities")]
    [System.SerializableAttribute()]
    public partial class BEEstado : WebDocuments.ServiceGeneral.Auditoria {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gls_estadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_estado {
            get {
                return this.cod_estadoField;
            }
            set {
                if ((this.cod_estadoField.Equals(value) != true)) {
                    this.cod_estadoField = value;
                    this.RaisePropertyChanged("cod_estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gls_estado {
            get {
                return this.gls_estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.gls_estadoField, value) != true)) {
                    this.gls_estadoField = value;
                    this.RaisePropertyChanged("gls_estado");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceGeneral.IGeneralService")]
    public interface IGeneralService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/ListarArea", ReplyAction="http://tempuri.org/IGeneralService/ListarAreaResponse")]
        WebDocuments.ServiceGeneral.BEArea[] ListarArea();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/ListarArea", ReplyAction="http://tempuri.org/IGeneralService/ListarAreaResponse")]
        System.Threading.Tasks.Task<WebDocuments.ServiceGeneral.BEArea[]> ListarAreaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/ListarRol", ReplyAction="http://tempuri.org/IGeneralService/ListarRolResponse")]
        WebDocuments.ServiceGeneral.BERol[] ListarRol();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/ListarRol", ReplyAction="http://tempuri.org/IGeneralService/ListarRolResponse")]
        System.Threading.Tasks.Task<WebDocuments.ServiceGeneral.BERol[]> ListarRolAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/ListarTipoDocumento", ReplyAction="http://tempuri.org/IGeneralService/ListarTipoDocumentoResponse")]
        WebDocuments.ServiceGeneral.BETipoDocumento[] ListarTipoDocumento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/ListarTipoDocumento", ReplyAction="http://tempuri.org/IGeneralService/ListarTipoDocumentoResponse")]
        System.Threading.Tasks.Task<WebDocuments.ServiceGeneral.BETipoDocumento[]> ListarTipoDocumentoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/ListarEstado", ReplyAction="http://tempuri.org/IGeneralService/ListarEstadoResponse")]
        WebDocuments.ServiceGeneral.BEEstado[] ListarEstado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/ListarEstado", ReplyAction="http://tempuri.org/IGeneralService/ListarEstadoResponse")]
        System.Threading.Tasks.Task<WebDocuments.ServiceGeneral.BEEstado[]> ListarEstadoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGeneralServiceChannel : WebDocuments.ServiceGeneral.IGeneralService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeneralServiceClient : System.ServiceModel.ClientBase<WebDocuments.ServiceGeneral.IGeneralService>, WebDocuments.ServiceGeneral.IGeneralService {
        
        public GeneralServiceClient() {
        }
        
        public GeneralServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeneralServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebDocuments.ServiceGeneral.BEArea[] ListarArea() {
            return base.Channel.ListarArea();
        }
        
        public System.Threading.Tasks.Task<WebDocuments.ServiceGeneral.BEArea[]> ListarAreaAsync() {
            return base.Channel.ListarAreaAsync();
        }
        
        public WebDocuments.ServiceGeneral.BERol[] ListarRol() {
            return base.Channel.ListarRol();
        }
        
        public System.Threading.Tasks.Task<WebDocuments.ServiceGeneral.BERol[]> ListarRolAsync() {
            return base.Channel.ListarRolAsync();
        }
        
        public WebDocuments.ServiceGeneral.BETipoDocumento[] ListarTipoDocumento() {
            return base.Channel.ListarTipoDocumento();
        }
        
        public System.Threading.Tasks.Task<WebDocuments.ServiceGeneral.BETipoDocumento[]> ListarTipoDocumentoAsync() {
            return base.Channel.ListarTipoDocumentoAsync();
        }
        
        public WebDocuments.ServiceGeneral.BEEstado[] ListarEstado() {
            return base.Channel.ListarEstado();
        }
        
        public System.Threading.Tasks.Task<WebDocuments.ServiceGeneral.BEEstado[]> ListarEstadoAsync() {
            return base.Channel.ListarEstadoAsync();
        }
    }
}
