//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDocuments.ServicePerfil {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEPerfil", Namespace="http://schemas.datacontract.org/2004/07/eDocuments.Entities")]
    [System.SerializableAttribute()]
    public partial class BEPerfil : WebDocuments.ServicePerfil.Auditoria {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_perfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gls_perfilField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_perfil {
            get {
                return this.cod_perfilField;
            }
            set {
                if ((this.cod_perfilField.Equals(value) != true)) {
                    this.cod_perfilField = value;
                    this.RaisePropertyChanged("cod_perfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gls_perfil {
            get {
                return this.gls_perfilField;
            }
            set {
                if ((object.ReferenceEquals(this.gls_perfilField, value) != true)) {
                    this.gls_perfilField = value;
                    this.RaisePropertyChanged("gls_perfil");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auditoria", Namespace="http://schemas.datacontract.org/2004/07/eDocuments.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDocuments.ServicePerfil.BEPerfilDocumento))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDocuments.ServicePerfil.BEPerfilUsuario))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDocuments.ServicePerfil.BEPerfil))]
    public partial class Auditoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime aud_fec_ingresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime aud_fec_modificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aud_usr_ingresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aud_usr_modificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_estado_registroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime aud_fec_ingreso {
            get {
                return this.aud_fec_ingresoField;
            }
            set {
                if ((this.aud_fec_ingresoField.Equals(value) != true)) {
                    this.aud_fec_ingresoField = value;
                    this.RaisePropertyChanged("aud_fec_ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime aud_fec_modificacion {
            get {
                return this.aud_fec_modificacionField;
            }
            set {
                if ((this.aud_fec_modificacionField.Equals(value) != true)) {
                    this.aud_fec_modificacionField = value;
                    this.RaisePropertyChanged("aud_fec_modificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aud_usr_ingreso {
            get {
                return this.aud_usr_ingresoField;
            }
            set {
                if ((object.ReferenceEquals(this.aud_usr_ingresoField, value) != true)) {
                    this.aud_usr_ingresoField = value;
                    this.RaisePropertyChanged("aud_usr_ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aud_usr_modificacion {
            get {
                return this.aud_usr_modificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.aud_usr_modificacionField, value) != true)) {
                    this.aud_usr_modificacionField = value;
                    this.RaisePropertyChanged("aud_usr_modificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_estado_registro {
            get {
                return this.cod_estado_registroField;
            }
            set {
                if ((this.cod_estado_registroField.Equals(value) != true)) {
                    this.cod_estado_registroField = value;
                    this.RaisePropertyChanged("cod_estado_registro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEPerfilDocumento", Namespace="http://schemas.datacontract.org/2004/07/eDocuments.Entities")]
    [System.SerializableAttribute()]
    public partial class BEPerfilDocumento : WebDocuments.ServicePerfil.Auditoria {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_perfilField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_documento {
            get {
                return this.cod_documentoField;
            }
            set {
                if ((this.cod_documentoField.Equals(value) != true)) {
                    this.cod_documentoField = value;
                    this.RaisePropertyChanged("cod_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_perfil {
            get {
                return this.cod_perfilField;
            }
            set {
                if ((this.cod_perfilField.Equals(value) != true)) {
                    this.cod_perfilField = value;
                    this.RaisePropertyChanged("cod_perfil");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEPerfilUsuario", Namespace="http://schemas.datacontract.org/2004/07/eDocuments.Entities")]
    [System.SerializableAttribute()]
    public partial class BEPerfilUsuario : WebDocuments.ServicePerfil.Auditoria {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_perfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gls_perfilField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_perfil {
            get {
                return this.cod_perfilField;
            }
            set {
                if ((this.cod_perfilField.Equals(value) != true)) {
                    this.cod_perfilField = value;
                    this.RaisePropertyChanged("cod_perfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_usuario {
            get {
                return this.cod_usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_usuarioField, value) != true)) {
                    this.cod_usuarioField = value;
                    this.RaisePropertyChanged("cod_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gls_perfil {
            get {
                return this.gls_perfilField;
            }
            set {
                if ((object.ReferenceEquals(this.gls_perfilField, value) != true)) {
                    this.gls_perfilField = value;
                    this.RaisePropertyChanged("gls_perfil");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePerfil.IPerfilService")]
    public interface IPerfilService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/ListarPerfil", ReplyAction="http://tempuri.org/IPerfilService/ListarPerfilResponse")]
        WebDocuments.ServicePerfil.BEPerfil[] ListarPerfil();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/ListarPerfil", ReplyAction="http://tempuri.org/IPerfilService/ListarPerfilResponse")]
        System.Threading.Tasks.Task<WebDocuments.ServicePerfil.BEPerfil[]> ListarPerfilAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/Registrar", ReplyAction="http://tempuri.org/IPerfilService/RegistrarResponse")]
        int Registrar(WebDocuments.ServicePerfil.BEPerfil oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/Registrar", ReplyAction="http://tempuri.org/IPerfilService/RegistrarResponse")]
        System.Threading.Tasks.Task<int> RegistrarAsync(WebDocuments.ServicePerfil.BEPerfil oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/Actualizar", ReplyAction="http://tempuri.org/IPerfilService/ActualizarResponse")]
        int Actualizar(WebDocuments.ServicePerfil.BEPerfil oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/Actualizar", ReplyAction="http://tempuri.org/IPerfilService/ActualizarResponse")]
        System.Threading.Tasks.Task<int> ActualizarAsync(WebDocuments.ServicePerfil.BEPerfil oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/Eliminar", ReplyAction="http://tempuri.org/IPerfilService/EliminarResponse")]
        int Eliminar(WebDocuments.ServicePerfil.BEPerfil oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/Eliminar", ReplyAction="http://tempuri.org/IPerfilService/EliminarResponse")]
        System.Threading.Tasks.Task<int> EliminarAsync(WebDocuments.ServicePerfil.BEPerfil oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/GetPerfilesSinAsignar", ReplyAction="http://tempuri.org/IPerfilService/GetPerfilesSinAsignarResponse")]
        WebDocuments.ServicePerfil.BEPerfil[] GetPerfilesSinAsignar(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/GetPerfilesSinAsignar", ReplyAction="http://tempuri.org/IPerfilService/GetPerfilesSinAsignarResponse")]
        System.Threading.Tasks.Task<WebDocuments.ServicePerfil.BEPerfil[]> GetPerfilesSinAsignarAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/GetPerfilesAsignados", ReplyAction="http://tempuri.org/IPerfilService/GetPerfilesAsignadosResponse")]
        WebDocuments.ServicePerfil.BEPerfil[] GetPerfilesAsignados(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/GetPerfilesAsignados", ReplyAction="http://tempuri.org/IPerfilService/GetPerfilesAsignadosResponse")]
        System.Threading.Tasks.Task<WebDocuments.ServicePerfil.BEPerfil[]> GetPerfilesAsignadosAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/GetPerfilesSinAsignarDoc", ReplyAction="http://tempuri.org/IPerfilService/GetPerfilesSinAsignarDocResponse")]
        WebDocuments.ServicePerfil.BEPerfil[] GetPerfilesSinAsignarDoc(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/GetPerfilesSinAsignarDoc", ReplyAction="http://tempuri.org/IPerfilService/GetPerfilesSinAsignarDocResponse")]
        System.Threading.Tasks.Task<WebDocuments.ServicePerfil.BEPerfil[]> GetPerfilesSinAsignarDocAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/GetPerfilesAsignadosDoc", ReplyAction="http://tempuri.org/IPerfilService/GetPerfilesAsignadosDocResponse")]
        WebDocuments.ServicePerfil.BEPerfil[] GetPerfilesAsignadosDoc(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/GetPerfilesAsignadosDoc", ReplyAction="http://tempuri.org/IPerfilService/GetPerfilesAsignadosDocResponse")]
        System.Threading.Tasks.Task<WebDocuments.ServicePerfil.BEPerfil[]> GetPerfilesAsignadosDocAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/RegistrarPerfilDocumento", ReplyAction="http://tempuri.org/IPerfilService/RegistrarPerfilDocumentoResponse")]
        int RegistrarPerfilDocumento(WebDocuments.ServicePerfil.BEPerfilDocumento oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/RegistrarPerfilDocumento", ReplyAction="http://tempuri.org/IPerfilService/RegistrarPerfilDocumentoResponse")]
        System.Threading.Tasks.Task<int> RegistrarPerfilDocumentoAsync(WebDocuments.ServicePerfil.BEPerfilDocumento oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/EliminarPerfilDocumento", ReplyAction="http://tempuri.org/IPerfilService/EliminarPerfilDocumentoResponse")]
        int EliminarPerfilDocumento(WebDocuments.ServicePerfil.BEPerfilDocumento oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/EliminarPerfilDocumento", ReplyAction="http://tempuri.org/IPerfilService/EliminarPerfilDocumentoResponse")]
        System.Threading.Tasks.Task<int> EliminarPerfilDocumentoAsync(WebDocuments.ServicePerfil.BEPerfilDocumento oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/ListarPerfilUsuario", ReplyAction="http://tempuri.org/IPerfilService/ListarPerfilUsuarioResponse")]
        WebDocuments.ServicePerfil.BEPerfilUsuario[] ListarPerfilUsuario(string cod_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/ListarPerfilUsuario", ReplyAction="http://tempuri.org/IPerfilService/ListarPerfilUsuarioResponse")]
        System.Threading.Tasks.Task<WebDocuments.ServicePerfil.BEPerfilUsuario[]> ListarPerfilUsuarioAsync(string cod_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/RegistrarPerfilUsuario", ReplyAction="http://tempuri.org/IPerfilService/RegistrarPerfilUsuarioResponse")]
        int RegistrarPerfilUsuario(WebDocuments.ServicePerfil.BEPerfilUsuario oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/RegistrarPerfilUsuario", ReplyAction="http://tempuri.org/IPerfilService/RegistrarPerfilUsuarioResponse")]
        System.Threading.Tasks.Task<int> RegistrarPerfilUsuarioAsync(WebDocuments.ServicePerfil.BEPerfilUsuario oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/EliminarPerfilUsuario", ReplyAction="http://tempuri.org/IPerfilService/EliminarPerfilUsuarioResponse")]
        int EliminarPerfilUsuario(WebDocuments.ServicePerfil.BEPerfilUsuario oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/EliminarPerfilUsuario", ReplyAction="http://tempuri.org/IPerfilService/EliminarPerfilUsuarioResponse")]
        System.Threading.Tasks.Task<int> EliminarPerfilUsuarioAsync(WebDocuments.ServicePerfil.BEPerfilUsuario oParametro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPerfilServiceChannel : WebDocuments.ServicePerfil.IPerfilService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PerfilServiceClient : System.ServiceModel.ClientBase<WebDocuments.ServicePerfil.IPerfilService>, WebDocuments.ServicePerfil.IPerfilService {
        
        public PerfilServiceClient() {
        }
        
        public PerfilServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PerfilServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerfilServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerfilServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebDocuments.ServicePerfil.BEPerfil[] ListarPerfil() {
            return base.Channel.ListarPerfil();
        }
        
        public System.Threading.Tasks.Task<WebDocuments.ServicePerfil.BEPerfil[]> ListarPerfilAsync() {
            return base.Channel.ListarPerfilAsync();
        }
        
        public int Registrar(WebDocuments.ServicePerfil.BEPerfil oParametro) {
            return base.Channel.Registrar(oParametro);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarAsync(WebDocuments.ServicePerfil.BEPerfil oParametro) {
            return base.Channel.RegistrarAsync(oParametro);
        }
        
        public int Actualizar(WebDocuments.ServicePerfil.BEPerfil oParametro) {
            return base.Channel.Actualizar(oParametro);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarAsync(WebDocuments.ServicePerfil.BEPerfil oParametro) {
            return base.Channel.ActualizarAsync(oParametro);
        }
        
        public int Eliminar(WebDocuments.ServicePerfil.BEPerfil oParametro) {
            return base.Channel.Eliminar(oParametro);
        }
        
        public System.Threading.Tasks.Task<int> EliminarAsync(WebDocuments.ServicePerfil.BEPerfil oParametro) {
            return base.Channel.EliminarAsync(oParametro);
        }
        
        public WebDocuments.ServicePerfil.BEPerfil[] GetPerfilesSinAsignar(string id) {
            return base.Channel.GetPerfilesSinAsignar(id);
        }
        
        public System.Threading.Tasks.Task<WebDocuments.ServicePerfil.BEPerfil[]> GetPerfilesSinAsignarAsync(string id) {
            return base.Channel.GetPerfilesSinAsignarAsync(id);
        }
        
        public WebDocuments.ServicePerfil.BEPerfil[] GetPerfilesAsignados(string id) {
            return base.Channel.GetPerfilesAsignados(id);
        }
        
        public System.Threading.Tasks.Task<WebDocuments.ServicePerfil.BEPerfil[]> GetPerfilesAsignadosAsync(string id) {
            return base.Channel.GetPerfilesAsignadosAsync(id);
        }
        
        public WebDocuments.ServicePerfil.BEPerfil[] GetPerfilesSinAsignarDoc(int id) {
            return base.Channel.GetPerfilesSinAsignarDoc(id);
        }
        
        public System.Threading.Tasks.Task<WebDocuments.ServicePerfil.BEPerfil[]> GetPerfilesSinAsignarDocAsync(int id) {
            return base.Channel.GetPerfilesSinAsignarDocAsync(id);
        }
        
        public WebDocuments.ServicePerfil.BEPerfil[] GetPerfilesAsignadosDoc(int id) {
            return base.Channel.GetPerfilesAsignadosDoc(id);
        }
        
        public System.Threading.Tasks.Task<WebDocuments.ServicePerfil.BEPerfil[]> GetPerfilesAsignadosDocAsync(int id) {
            return base.Channel.GetPerfilesAsignadosDocAsync(id);
        }
        
        public int RegistrarPerfilDocumento(WebDocuments.ServicePerfil.BEPerfilDocumento oParametro) {
            return base.Channel.RegistrarPerfilDocumento(oParametro);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarPerfilDocumentoAsync(WebDocuments.ServicePerfil.BEPerfilDocumento oParametro) {
            return base.Channel.RegistrarPerfilDocumentoAsync(oParametro);
        }
        
        public int EliminarPerfilDocumento(WebDocuments.ServicePerfil.BEPerfilDocumento oParametro) {
            return base.Channel.EliminarPerfilDocumento(oParametro);
        }
        
        public System.Threading.Tasks.Task<int> EliminarPerfilDocumentoAsync(WebDocuments.ServicePerfil.BEPerfilDocumento oParametro) {
            return base.Channel.EliminarPerfilDocumentoAsync(oParametro);
        }
        
        public WebDocuments.ServicePerfil.BEPerfilUsuario[] ListarPerfilUsuario(string cod_usuario) {
            return base.Channel.ListarPerfilUsuario(cod_usuario);
        }
        
        public System.Threading.Tasks.Task<WebDocuments.ServicePerfil.BEPerfilUsuario[]> ListarPerfilUsuarioAsync(string cod_usuario) {
            return base.Channel.ListarPerfilUsuarioAsync(cod_usuario);
        }
        
        public int RegistrarPerfilUsuario(WebDocuments.ServicePerfil.BEPerfilUsuario oParametro) {
            return base.Channel.RegistrarPerfilUsuario(oParametro);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarPerfilUsuarioAsync(WebDocuments.ServicePerfil.BEPerfilUsuario oParametro) {
            return base.Channel.RegistrarPerfilUsuarioAsync(oParametro);
        }
        
        public int EliminarPerfilUsuario(WebDocuments.ServicePerfil.BEPerfilUsuario oParametro) {
            return base.Channel.EliminarPerfilUsuario(oParametro);
        }
        
        public System.Threading.Tasks.Task<int> EliminarPerfilUsuarioAsync(WebDocuments.ServicePerfil.BEPerfilUsuario oParametro) {
            return base.Channel.EliminarPerfilUsuarioAsync(oParametro);
        }
    }
}
